export default function SideBar() {
    return (
        <div className="flex items-center shrink-0 w-[20rem] bg-white h-full mr-[1.5rem]">
            <div className='h-[95%] overflow-auto p-8'>
                <p className='text-center'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim praesent elementum facilisis leo vel fringilla est ullamcorper eget. Imperdiet proin fermentum leo vel orci porta non. Ridiculus mus mauris vitae ultricies leo integer. Elit duis tristique sollicitudin nibh sit amet commodo nulla. Elit eget gravida cum sociis natoque penatibus et. Cum sociis natoque penatibus et magnis dis. Id aliquet lectus proin nibh nisl condimentum. Nunc id cursus metus aliquam eleifend mi. <br /><br /> Cursus risus at ultrices mi tempus imperdiet. Nullam non nisi est sit amet facilisis. Nec tincidunt praesent semper feugiat nibh sed. Quis commodo odio aenean sed. Fermentum et sollicitudin ac orci. Enim neque volutpat ac tincidunt vitae. <br /><br />
                    Habitasse platea dictumst quisque sagittis purus. Ac felis donec et odio pellentesque diam. Sed elementum tempus egestas sed sed. Enim sit amet venenatis urna cursus eget nunc. Id aliquet risus feugiat in. Habitasse platea dictumst quisque sagittis purus. Erat velit scelerisque in dictum non consectetur. Sed turpis tincidunt id aliquet risus feugiat in. Ac felis donec et odio pellentesque diam. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Mattis nunc sed blandit libero volutpat sed cras ornare. Et odio pellentesque diam volutpat commodo sed. Viverra justo nec ultrices dui sapien. Fringilla phasellus faucibus scelerisque eleifend donec.  <br /><br />Et netus et malesuada fames ac turpis egestas sed tempus. Dignissim enim sit amet venenatis. Enim diam vulputate ut pharetra sit amet aliquam id.
                    Non sodales neque sodales ut etiam sit amet. Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Iaculis nunc sed augue lacus viverra vitae congue eu consequat. Et malesuada fames ac turpis egestas maecenas pharetra convallis. Sit amet nulla facilisi morbi tempus iaculis. Enim ut sem viverra aliquet eget sit. Odio eu feugiat pretium nibh ipsum consequat nisl. Magna sit amet purus gravida quis. Facilisi cras fermentum odio eu feugiat pretium. Sed turpis tincidunt id aliquet risus. Amet nulla facilisi morbi tempus iaculis urna id volutpat. <br /><br /> Vel pretium lectus quam id leo in vitae turpis. Urna molestie at elementum eu facilisis sed.
                </p>
            </div>
        </div>)
}
